"""additioanl schema

Revision ID: 160c26bff4dd
Revises: 4fb77af04a42
Create Date: 2024-01-21 20:28:18.594848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160c26bff4dd'
down_revision: Union[str, None] = '4fb77af04a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_id'], ['c_health_information.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_id', sa.Integer(), nullable=True),
    sa.Column('vaccination_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_id'], ['c_health_information.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination_history')
    op.drop_table('medical_history')
    # ### end Alembic commands ###
