"""health

Revision ID: 5dd98365f721
Revises: 8ef5441d86b9
Create Date: 2024-01-23 10:27:49.409843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd98365f721'
down_revision: Union[str, None] = '8ef5441d86b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_records', sa.Column('vaccine', sa.String(), nullable=True))
    op.add_column('vaccination_records', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('vaccination_records', sa.Column('dose', sa.String(), nullable=True))
    op.drop_column('vaccination_records', 'immunizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_records', sa.Column('immunizations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('vaccination_records', 'dose')
    op.drop_column('vaccination_records', 'date')
    op.drop_column('vaccination_records', 'vaccine')
    # ### end Alembic commands ###
