"""added table and edited metadata

Revision ID: 6c814136a832
Revises: d6a276243dd8
Create Date: 2024-02-27 23:20:13.375987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c814136a832'
down_revision: Union[str, None] = 'd6a276243dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccines',
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vaccine_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    # ### end Alembic commands ###
