"""added users and some revisions

Revision ID: 7660d622e6da
Revises: 
Create Date: 2024-01-23 22:22:09.584708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7660d622e6da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('AnnouncementID', sa.Integer(), nullable=False),
    sa.Column('AnnouncementTitle', sa.String(), nullable=False),
    sa.Column('AnnouncementContent', sa.Text(), nullable=True),
    sa.Column('AnnouncementDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Announcer', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('AnnouncementID')
    )
    op.create_index(op.f('ix_announcements_AnnouncementID'), 'announcements', ['AnnouncementID'], unique=False)
    op.create_index(op.f('ix_announcements_AnnouncementTitle'), 'announcements', ['AnnouncementTitle'], unique=False)
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcements_created_by'), 'announcements', ['created_by'], unique=False)
    op.create_index(op.f('ix_announcements_updated_at'), 'announcements', ['updated_at'], unique=False)
    op.create_index(op.f('ix_announcements_updated_by'), 'announcements', ['updated_by'], unique=False)
    op.create_table('budget_tracking',
    sa.Column('BudgetID', sa.Integer(), nullable=False),
    sa.Column('BudgetName', sa.String(), nullable=False),
    sa.Column('BudgetAmount', sa.Integer(), nullable=False),
    sa.Column('Expenditure', sa.Integer(), nullable=False),
    sa.Column('TransactionDate', sa.DateTime(), nullable=True),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('BudgetID')
    )
    op.create_index(op.f('ix_budget_tracking_BudgetID'), 'budget_tracking', ['BudgetID'], unique=False)
    op.create_index(op.f('ix_budget_tracking_BudgetName'), 'budget_tracking', ['BudgetName'], unique=False)
    op.create_index(op.f('ix_budget_tracking_created_at'), 'budget_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_budget_tracking_created_by'), 'budget_tracking', ['created_by'], unique=False)
    op.create_index(op.f('ix_budget_tracking_updated_at'), 'budget_tracking', ['updated_at'], unique=False)
    op.create_index(op.f('ix_budget_tracking_updated_by'), 'budget_tracking', ['updated_by'], unique=False)
    op.create_table('community_events',
    sa.Column('EventID', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(), nullable=False),
    sa.Column('EventType', sa.String(), nullable=True),
    sa.Column('EventDate', sa.DateTime(), nullable=True),
    sa.Column('EventLocation', sa.String(), nullable=True),
    sa.Column('Organizer', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EventID')
    )
    op.create_index(op.f('ix_community_events_EventID'), 'community_events', ['EventID'], unique=False)
    op.create_index(op.f('ix_community_events_EventName'), 'community_events', ['EventName'], unique=False)
    op.create_index(op.f('ix_community_events_EventType'), 'community_events', ['EventType'], unique=False)
    op.create_index(op.f('ix_community_events_created_at'), 'community_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_events_created_by'), 'community_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_community_events_updated_at'), 'community_events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_community_events_updated_by'), 'community_events', ['updated_by'], unique=False)
    op.create_table('health_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('is_dead', sa.Boolean(), server_default=sa.text('False'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_information_full_name'), 'health_information', ['full_name'], unique=False)
    op.create_index(op.f('ix_health_information_id'), 'health_information', ['id'], unique=False)
    op.create_index(op.f('ix_health_information_updated_by'), 'health_information', ['updated_by'], unique=False)
    op.create_table('revenue_collection',
    sa.Column('RevenueID', sa.Integer(), nullable=False),
    sa.Column('SourceName', sa.String(), nullable=False),
    sa.Column('CollectionAmount', sa.Integer(), nullable=False),
    sa.Column('CollectionDate', sa.DateTime(), nullable=True),
    sa.Column('Note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('RevenueID')
    )
    op.create_index(op.f('ix_revenue_collection_RevenueID'), 'revenue_collection', ['RevenueID'], unique=False)
    op.create_index(op.f('ix_revenue_collection_SourceName'), 'revenue_collection', ['SourceName'], unique=False)
    op.create_index(op.f('ix_revenue_collection_created_at'), 'revenue_collection', ['created_at'], unique=False)
    op.create_index(op.f('ix_revenue_collection_created_by'), 'revenue_collection', ['created_by'], unique=False)
    op.create_index(op.f('ix_revenue_collection_updated_at'), 'revenue_collection', ['updated_at'], unique=False)
    op.create_index(op.f('ix_revenue_collection_updated_by'), 'revenue_collection', ['updated_by'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('False'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('person_info', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_info'], ['health_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_contact_name'), 'emergency_contacts', ['contact_name'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_updated_by'), 'emergency_contacts', ['updated_by'], unique=False)
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('surgeries', sa.JSON(), nullable=True),
    sa.Column('family_history', sa.JSON(), nullable=True),
    sa.Column('person_info', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_info'], ['health_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_id'), 'medical_history', ['id'], unique=False)
    op.create_index(op.f('ix_medical_history_updated_by'), 'medical_history', ['updated_by'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('illness', sa.String(), nullable=True),
    sa.Column('medicine', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('diagnosed_date', sa.DATE(), nullable=True),
    sa.Column('person_info', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_info'], ['health_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_updated_by'), 'medications', ['updated_by'], unique=False)
    op.create_table('vaccination_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaccine', sa.String(), nullable=True),
    sa.Column('vaccinated_date', sa.DATE(), nullable=True),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('person_info', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default=sa.text("'admin'"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_info'], ['health_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_id'), 'vaccination_records', ['id'], unique=False)
    op.create_index(op.f('ix_vaccination_records_updated_by'), 'vaccination_records', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccination_records_updated_by'), table_name='vaccination_records')
    op.drop_index(op.f('ix_vaccination_records_id'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_index(op.f('ix_medications_updated_by'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_history_updated_by'), table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_emergency_contacts_updated_by'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_contact_name'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_table('users')
    op.drop_index(op.f('ix_revenue_collection_updated_by'), table_name='revenue_collection')
    op.drop_index(op.f('ix_revenue_collection_updated_at'), table_name='revenue_collection')
    op.drop_index(op.f('ix_revenue_collection_created_by'), table_name='revenue_collection')
    op.drop_index(op.f('ix_revenue_collection_created_at'), table_name='revenue_collection')
    op.drop_index(op.f('ix_revenue_collection_SourceName'), table_name='revenue_collection')
    op.drop_index(op.f('ix_revenue_collection_RevenueID'), table_name='revenue_collection')
    op.drop_table('revenue_collection')
    op.drop_index(op.f('ix_health_information_updated_by'), table_name='health_information')
    op.drop_index(op.f('ix_health_information_id'), table_name='health_information')
    op.drop_index(op.f('ix_health_information_full_name'), table_name='health_information')
    op.drop_table('health_information')
    op.drop_index(op.f('ix_community_events_updated_by'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_updated_at'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_created_by'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_created_at'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_EventType'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_EventName'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_EventID'), table_name='community_events')
    op.drop_table('community_events')
    op.drop_index(op.f('ix_budget_tracking_updated_by'), table_name='budget_tracking')
    op.drop_index(op.f('ix_budget_tracking_updated_at'), table_name='budget_tracking')
    op.drop_index(op.f('ix_budget_tracking_created_by'), table_name='budget_tracking')
    op.drop_index(op.f('ix_budget_tracking_created_at'), table_name='budget_tracking')
    op.drop_index(op.f('ix_budget_tracking_BudgetName'), table_name='budget_tracking')
    op.drop_index(op.f('ix_budget_tracking_BudgetID'), table_name='budget_tracking')
    op.drop_table('budget_tracking')
    op.drop_index(op.f('ix_announcements_updated_by'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_updated_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_by'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_AnnouncementTitle'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_AnnouncementID'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
