"""health

Revision ID: 8ef5441d86b9
Revises: 
Create Date: 2024-01-23 03:40:59.328105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef5441d86b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_name'), 'emergency_contacts', ['name'], unique=False)
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('surgeries', sa.JSON(), nullable=True),
    sa.Column('family_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_id'), 'medical_history', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('vaccination_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immunizations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_id'), 'vaccination_records', ['id'], unique=False)
    op.create_table('health_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('barangay_id', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.Integer(), nullable=True),
    sa.Column('medical_history', sa.Integer(), nullable=True),
    sa.Column('vaccination_record', sa.Integer(), nullable=True),
    sa.Column('current_medications', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_medications'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['emergency_contact'], ['emergency_contacts.id'], ),
    sa.ForeignKeyConstraint(['medical_history'], ['medical_history.id'], ),
    sa.ForeignKeyConstraint(['vaccination_record'], ['vaccination_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_information_full_name'), 'health_information', ['full_name'], unique=False)
    op.create_index(op.f('ix_health_information_id'), 'health_information', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_information_id'), table_name='health_information')
    op.drop_index(op.f('ix_health_information_full_name'), table_name='health_information')
    op.drop_table('health_information')
    op.drop_index(op.f('ix_vaccination_records_id'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_history_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_emergency_contacts_name'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    # ### end Alembic commands ###
