"""all

Revision ID: 92dc91546bbd
Revises: 833efb2ad331
Create Date: 2024-01-21 18:08:43.147017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dc91546bbd'
down_revision: Union[str, None] = '833efb2ad331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_health_information', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('c_health_information', 'hi_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('c_health_information', sa.Column('hi_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('c_health_information', 'id')
    # ### end Alembic commands ###
