"""removed JSON

Revision ID: d6a276243dd8
Revises: e03107ebf8ef
Create Date: 2024-02-05 10:26:01.960057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6a276243dd8'
down_revision: Union[str, None] = 'e03107ebf8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_history', sa.Column('allergy', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('allergy_type', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('allergy_severity', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('chronic_condition', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('chronic_diagnosis', sa.DATE(), nullable=True))
    op.add_column('medical_history', sa.Column('surgery', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('surgery_date', sa.DATE(), nullable=True))
    op.add_column('medical_history', sa.Column('family_history_condition', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('family_history_relation', sa.String(), nullable=True))
    op.drop_column('medical_history', 'surgeries')
    op.drop_column('medical_history', 'allergies')
    op.drop_column('medical_history', 'chronic_conditions')
    op.drop_column('medical_history', 'family_history')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('medical_history', sa.Column('family_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('medical_history', sa.Column('chronic_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('medical_history', sa.Column('allergies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('medical_history', sa.Column('surgeries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('medical_history', 'family_history_relation')
    op.drop_column('medical_history', 'family_history_condition')
    op.drop_column('medical_history', 'surgery_date')
    op.drop_column('medical_history', 'surgery')
    op.drop_column('medical_history', 'chronic_diagnosis')
    op.drop_column('medical_history', 'chronic_condition')
    op.drop_column('medical_history', 'allergy_severity')
    op.drop_column('medical_history', 'allergy_type')
    op.drop_column('medical_history', 'allergy')
    # ### end Alembic commands ###
