"""add

Revision ID: e03107ebf8ef
Revises: 49498f8caf9e
Create Date: 2024-01-26 12:43:56.576952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03107ebf8ef'
down_revision: Union[str, None] = '49498f8caf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emergency_contacts_person_info_fkey', 'emergency_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'emergency_contacts', 'health_information', ['person_info'], ['id'], ondelete='CASCADE')
    op.drop_constraint('medical_history_person_info_fkey', 'medical_history', type_='foreignkey')
    op.create_foreign_key(None, 'medical_history', 'health_information', ['person_info'], ['id'], ondelete='CASCADE')
    op.drop_constraint('medications_person_info_fkey', 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'health_information', ['person_info'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint('vaccination_records_person_info_fkey', 'vaccination_records', type_='foreignkey')
    op.create_foreign_key(None, 'vaccination_records', 'health_information', ['person_info'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccination_records', type_='foreignkey')
    op.create_foreign_key('vaccination_records_person_info_fkey', 'vaccination_records', 'health_information', ['person_info'], ['id'])
    op.drop_column('users', 'is_deleted')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.create_foreign_key('medications_person_info_fkey', 'medications', 'health_information', ['person_info'], ['id'])
    op.drop_constraint(None, 'medical_history', type_='foreignkey')
    op.create_foreign_key('medical_history_person_info_fkey', 'medical_history', 'health_information', ['person_info'], ['id'])
    op.drop_constraint(None, 'emergency_contacts', type_='foreignkey')
    op.create_foreign_key('emergency_contacts_person_info_fkey', 'emergency_contacts', 'health_information', ['person_info'], ['id'])
    # ### end Alembic commands ###
