from faker import Faker
from datetime import datetime, timedelta, timezone
import random
import json

fake = Faker()

# Generate random date within 2020-2024
def generate_random_date():
    start_date = datetime(2020, 1, 1, tzinfo=timezone.utc)
    end_date = datetime(2024, 12, 31, tzinfo=timezone.utc)
    random_seconds = random.randint(0, int((end_date - start_date).total_seconds()))
    return start_date + timedelta(seconds=random_seconds)


medicines = [
  "Aspirin",
  "Ibuprofen",
  "Acetaminophen",
  "Amoxicillin",
  "Lisinopril",
  "Atorvastatin",
  "Metformin",
  "Omeprazole",
  "Albuterol",
  "Hydrochlorothiazide",
  "Levothyroxine",
  "Prednisone",
  "Simvastatin",
  "Losartan",
  "Gabapentin",
  "Azithromycin",
  "Citalopram",
  "Amlodipine",
  "Doxycycline",
  "Warfarin",
  "Ciprofloxacin",
  "Fluoxetine",
  "Ranitidine",
  "Tramadol",
  "Clonazepam",
  "Sertraline",
  "Metoprolol",
  "Escitalopram",
  "Venlafaxine",
  "Methotrexate",
  "Carvedilol",
  "Furosemide",
  "Clopidogrel",
  "Duloxetine",
  "Insulin",
  "Lorazepam",
  "Montelukast",
  "Trazodone",
  "Hydroxyzine",
  "Sildenafil",
  "Aripiprazole",
  "Pregabalin",
  "Risperidone",
  "Bupropion",
  "Diazepam",
  "Naproxen",
  "Quetiapine",
  "Meloxicam",
  "Loratadine",
  "Pantoprazole",
  "Mirtazapine",
  "Amitriptyline",
  "Tamsulosin",
  "Dexamethasone",
  "Methylphenidate",
  "Olanzapine",
  "Levofloxacin",
  "Celecoxib",
  "Esomeprazole",
  "Hydrocortisone",
  "Mometasone",
  "Vitamin D",
  "Fish Oil",
  "Calcium Carbonate",
  "Potassium Chloride",
  "Multivitamin",
  "Iodine",
  "Magnesium Citrate",
  "Folic Acid",
  "Iron Supplement",
  "Vitamin C",
  "Zinc Oxide",
  "Vitamin B12",
  "Omega-3 Fatty Acids"
]

illnesses = [
  "Influenza (Flu)",
  "Common Cold",
  "Pneumonia",
  "Bronchitis",
  "Asthma",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Diabetes Mellitus",
  "Hypertension (High Blood Pressure)",
  "Coronary Artery Disease (CAD)",
  "Myocardial Infarction (Heart Attack)",
  "Stroke (Cerebrovascular Accident)",
  "Arthritis",
  "Osteoporosis",
  "Rheumatoid Arthritis",
  "Gout",
  "Cancer (Various Types)",
  "HIV/AIDS",
  "Hepatitis (Various Types)",
  "Tuberculosis (TB)",
  "Malaria",
  "Cholera",
  "Dengue Fever",
  "Zika Virus",
  "Ebola",
  "Alzheimers Disease",
  "Parkinsons Disease",
  "Multiple Sclerosis (MS)",
  "Epilepsy",
  "Migraine",
  "Depression",
  "Anxiety Disorders",
  "Bipolar Disorder",
  "Schizophrenia",
  "Obsessive-Compulsive Disorder (OCD)",
  "Post-Traumatic Stress Disorder (PTSD)",
  "Attention-Deficit/Hyperactivity Disorder (ADHD)",
  "Autism Spectrum Disorder",
  "Crohn Disease",
  "Ulcerative Colitis",
  "Irritable Bowel Syndrome (IBS)",
  "Chronic Kidney Disease",
  "Urinary Tract Infection (UTI)",
  "Gastroesophageal Reflux Disease (GERD)",
  "Celiac Disease",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Endometriosis",
  "Polycystic Ovary Syndrome (PCOS)",
  "Fibromyalgia",
  "Chronic Fatigue Syndrome (CFS)"
]

dosages = [
  "Take 1 tablet every 4-6 hours as needed",
  "Take 2 capsules daily with food",
  "Inject 0.5 mL subcutaneously once a week",
  "Apply a thin layer of cream to the affected area twice daily",
  "Take 500 mg orally three times a day",
  "Inhale 2 puffs every 4-6 hours as directed",
  "Administer 10 units subcutaneously before meals",
  "Take 20 mg orally at bedtime",
  "Apply eye drops to affected eye(s) every 8-12 hours",
  "Take 1 tablespoon by mouth every morning",
  "Use nasal spray, 1 spray in each nostril twice daily",
  "Consume 250 mL of syrup three times a day",
  "Chew 2 gummies daily after a meal",
  "Insert one suppository rectally as needed",
  "Dissolve 1 effervescent tablet in water daily",
  "Take 50 mg sublingually every 6 hours",
  "Administer 100 mg/mL solution via intramuscular injection",
  "Use topical solution sparingly on affected skin once daily",
  "Take 5 drops under the tongue twice a day",
  "Consume 1 lozenge every 2 hours for sore throat relief",
  "Apply a patch to clean, dry skin once every 24 hours",
  "Inhale 1 deep breath using the inhaler twice daily",
  "Administer 15 mg/kg body weight orally as a single dose",
  "Spray 1 metered dose into each nostril every 12 hours",
  "Use 2 pumps of gel on affected joints twice daily",
  "Take 1 extended-release capsule daily in the morning",
  "Apply ointment to the affected area every 8 hours",
  "Administer 2.5 mL suspension every 6 hours as needed",
  "Consume 1 teaspoon of solution before meals",
  "Take 2 lozenges at the onset of symptoms, then 1 lozenge every 4 hours",
  "Insert one vaginal suppository at bedtime for 7 days",
  "Apply a generous amount of lotion to dry skin once daily",
  "Take 1 softgel with a full glass of water daily",
  "Administer 3 drops in each eye every 8 hours",
  "Use 1 sachet of powder mixed with water every morning",
  "Chew 1 tablet thoroughly before swallowing, twice daily"
]

frequencies = [
  "Every 4-6 hours as needed",
  "Daily with food",
  "Once a week",
  "Twice daily",
  "Three times a day",
  "Every 8-12 hours",
  "Before meals",
  "At bedtime",
  "Every morning",
  "Twice a day",
  "Three times a day",
  "After a meal",
  "As needed",
  "Twice daily",
  "Every 2 hours",
  "Once every 24 hours",
  "Twice daily",
  "Daily",
  "Every 6 hours",
  "Every 12 hours",
  "Once a day",
  "In the morning",
  "Every 8 hours",
  "Every 4 hours",
  "Every 6 hours",
  "Once every 6 hours",
  "Every 3 hours",
  "Once every 8 hours",
  "Every 24 hours",
  "Every 4 hours as needed",
  "Every 2 hours for sore throat relief",
  "At the onset of symptoms, then every 4 hours",
  "Once at bedtime for 7 days",
  "Once daily",
  "Every 8 hours",
  "Every morning",
  "Every 4 hours as needed",
  "Twice daily",
  "Once every 8 hours",
  "Every 6 hours as needed",
  "Twice daily",
  "Once every 4 hours",
  "As needed",
  "Every 4 hours",
  "Once every 8-12 hours",
  "Every 12 hours"
]


# Generate random medication data for the Medication model
for i in range(1, 40):
    illness = random.choice(illnesses)
    medicine = random.choice(medicines)
    dosage = random.choice(dosages)
    frequency = random.choice(frequencies)
    diagnosed_date = generate_random_date().strftime('%Y-%m-%d')
    person_info = random.randint(1, 200)
    created_at = generate_random_date().strftime('%Y-%m-%d %H:%M:%S %z')

    insert_query = f"INSERT INTO medications (illness, medicine, dosage, frequency, diagnosed_date, person_info, created_at) " \
                   f"VALUES ('{illness}', '{medicine}', '{dosage}', '{frequency}', '{diagnosed_date}', {person_info}, '{created_at}');"

    print(insert_query)
